#!/bin/sh
################################################
#
# syncSSH
# 
# Version: 0.0.3 (2012AUG21)
################################################

# Setup script variables
APP_VERSION="0.0.3"
APP_NAME="syncSSH"
APP_DATE="2012AUG21"
APP_DESC="A wrapper script for using rsync over ssh."

# Usage Information
APP_USAGE="$(basename $0) $APP_VERSION $APP_DESC
Usage:
    -h,--help                       Alias of usage (-u, --usage)
    
    -H,--remote-host [user@]host    IP or DNS name of the ssh remote host.
                                        *NOT IMPLIMENTED*
                                        
    -k,--keyfile keyfile            Path to the key file to use for
                                    authentication.
                                    (default: $HOME/.ssh/id_rsa)
                                        *NOT IMPLIMENTED*
                                        
    -l,--local-path localpath       Local path, source path for syncing.
                                    (default: current directory)
                                        *NOT IMPLIMENTED*
                                        
    -p,--port port                  SSH port to use.
                                        *NOT IMPLIMENTED*
                                        
    -q,--quiet                      Run quietly with no output.
    
    -r,--remote-path remotepath     Remote path, destination path on
                                    remote host for syncing.
                                        *NOT IMPLIMENTED*
                                        
    -u,--usage                      Display the help/usage information.
    
    -v,--verbose                    Verbose mode.  Causes script to print
                                    debugging messages about its progress.
                                    This is helpful in debugging connection,
                                    authentication, and configuration problems.
                                    Multiple -v options increase the verbosity.
                                    The maximum is 3.
                                    
    -V,--version                    Display the version number and exit."

# Process parameters
for arg
do
    echo $arg
	case $arg in
		-vv* | --verbose)
			# verbose
			APP_VERBOSE=$arg 
			;;
			
		-q | --quiet)
			# quiet mode
			APP_QUIET=">& /dev/null"
			;;

		-V | --version)
			# version
			echo "$APP_NAME v$APP_VERSION ($APP_DATE)"
			exit
			;;
		
		-u | -h | --usage | --help)
		    # usage
		    echo "$APP_USAGE"
		    exit
		    ;;
		    
		-k | --keyfile)
		    # keyfile
		    shift
		    echo "$arg"
		    exit
		    ;;
		    
		*)
			# unknown variable
			if [ "$APP_PARAM_ERROR" != "" ]
			then
				APP_PARAM_ERROR="$APP_PARAM_ERROR, $arg"
			else
				APP_PARAM_ERROR="Unknown Parameter(s): $arg"
			fi
			;;	
	
	esac

done

# Check for errors in parameters
if [ "$APP_PARAM_ERROR" != "" ]
then
	printf '\a'
	echo -e "$APP_NAME ($APP_VERSION): ABORTED\n$APP_PARAM_ERROR"
	exit
fi

# Setup Keyfile
if [ "$KEYFILE" = "" ]
then
    KEYFILE="$HOME/.ssh/id_rsa"
fi

#KEYFILE="/home/jpscharf/keys/rsync-svn-serenity"

# Setup Local Path
LOCAL_PATH="/home/jpscharf/svn_backups/"

# Setup remote path
REMOTE_PATH="/volume1/NetBackup/svn/"

# Setup SSH Host
SSH_HOST="jasonscharf.org"

# Setup ssh command
SSH_COM="ssh $APP_VERBOSE -p 7822 -oPreferredAuthentications=publickey -i $KEYFILE"

# Setup rsync command
RSYNC_COM="rsync -azl $APP_VERBOSE -e \"$SSH_COM\" $SSH_HOST:$REMOTE_PATH $LOCAL_PATH"

if [ "$APP_QUIET" = "" ]
then

	echo "################################################"
	echo $APP_VERSION $APP_NAME
	echo "################################################"

	echo "Keyfile Setup: $KEYFILE"
	echo "Local path configured: $LOCAL_PATH"
	echo "Remote path configure: $REMOTE_PATH"
	echo "SSH host configured: $SSH_HOST"
	echo -e "SSH command generated:\n$SSH_COM"
	echo -e  "rsync command generated:\n$RSYNC_COM"
	echo "Running...."
fi

# Run rsync
# eval $RSYNC_COM $APP_QUIET

# wrap up
# exit $?

#rsync -azlvvv -e $SSHCOM:/volume1/NetBackup/svn/ /home/jpscharf/svn_backups
#rsync -azlvvv -e $SSHCOM $SSHHOST:$REMOTE_PATH $LOCAL_PATH

# ssh -vvv -oPreferredAuthentications=publickey root@192.168
#  
#rsync -azl -e "ssh -p7822" /home/jpscharf/svn_backups/ root@jasonscharf.org:/volume1/NetBackup/svn/
#rsync -azlvvv -e "ssh -vvvv -p7822 -i /home/jpscharf/keys/rsync-svn-serenity" 
#jasonscharf.org:/volume1/NetBackup/svn/ /home/jpscharf/svn_backups/
